#!/usr/bin/env python3
"""
Seed Codex typed blocks from block JSON.

    python3 seed_blocks.py blocks_*.json --emit-sql > seed.sql

Emits SQL to stdout. Writes nothing to the database — review the SQL,
then apply it yourself. That is deliberate: this script replaces existing
concept units, and you should see exactly what it removes first.

Strategy
--------
A file carrying "los", "practice" or "recap" authors the whole reading, so the
reading is deleted and rebuilt: los at ord 0, concepts at 1..N, practice, then
recap. Ordinals come out clean and nothing PDF-derived survives.

A file with only "units" is a v1 file. Concept and example units are removed
(a worked example belongs inside the concept it teaches, as a `worked` block —
the standalone example units are a PDF-pipeline artefact) and the survivors are
shifted past the new concepts through a staging range, because codex_units has
a non-deferrable unique (reading_id, ord) that Postgres checks per row.

Unit ids are a deterministic hash of (topic, module, ordinal, kind), so
re-running produces identical ids and the ON CONFLICT clauses make it
idempotent. Concept ids omit the kind, keeping ids already seeded stable.
"""
import json, sys, hashlib, argparse

# reading_id per module, from codex_documents where topic_id='alt'
READINGS = {
    "LM1": "9e4f73e51fc88d63",
    "LM2": "ee918d2241cca38f",
    "LM3": "e74131b7a8c16067",
    "LM4": "f74779747e1f9673",
}

# staging range for the ordinal shift — comfortably above any real ordinal, so
# neither leg of the two-step move can land on an occupied slot
PARK = 1000

def unit_id(topic, module, ordinal, kind="concept"):
    """
    16-char hex, matching the existing id format.

    `kind` is part of the key so a practice item and a concept unit sharing an
    ordinal get different ids. Concept ids omit it, which keeps every id already
    seeded for Alternatives stable — re-applying a v1 file is still idempotent.
    """
    tail = "" if kind == "concept" else f":{kind}"
    return hashlib.sha256(f"{topic}:{module}:{ordinal}{tail}:blocks-v1".encode()).hexdigest()[:16]

def q(s):
    """Quote a SQL string literal."""
    return "'" + str(s).replace("'", "''") + "'"

def jq(o):
    """Quote a JSON value as a jsonb literal."""
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"

def _words(o):
    """Count words in payload text only, ignoring JSON structure."""
    if isinstance(o, str):  return len(o.split())
    if isinstance(o, list): return sum(_words(x) for x in o)
    if isinstance(o, dict): return sum(_words(v) for k, v in o.items()
                                       if k not in ("aligns", "variant", "total_rows"))
    return 0

def est_minutes(blocks):
    """
    Technical study material reads at roughly 130 wpm, not the 200+ of casual
    prose. Tables, formulas and worked examples are parsed rather than read,
    so they carry a per-item surcharge in seconds.
    """
    SURCHARGE = {"formula": 25, "worked": 100, "key": 20, "trap": 20, "exam": 20,
                 "table_compare": 20, "table_signal": 15, "table_data": 20}
    seconds = 0
    for b in blocks:
        bt = b["block_type"]
        seconds += _words(b["payload"]) / 130 * 60
        seconds += SURCHARGE.get(bt, 0)
        if bt.startswith("table"):
            seconds += 12 * len(b["payload"].get("rows", []))
        if bt == "worked":
            seconds += 12 * sum(len(x.get("rows", []))
                                for x in b["payload"].get("blocks", [])
                                if x.get("kind") == "table")
    return max(3, min(20, round(seconds / 60)))

def emit(files):
    out = []
    A = out.append
    A("-- Generated by seed_blocks.py. Review before applying.")
    A("-- Rebuilds each reading from authored blocks.\n")
    A("begin;\n")

    for path in files:
        d = json.load(open(path, encoding="utf8"))
        mod, topic = d["module"], d["topic_id"]
        # reading_id belongs in the file. The hardcoded map does not scale to the
        # remaining readings and mis-targets silently when a module number
        # repeats across topics, which it does.
        reading = d.get("reading_id") or READINGS.get(mod)
        if not reading:
            sys.exit(f"{path}: no reading_id, and {mod} is not in READINGS")

        n_units = len(d["units"])
        A(f"-- ===== {mod}: {d['module_title']} =====")
        A(f"-- {n_units} units, {sum(len(u['blocks']) for u in d['units'])} blocks")

        # 1. rebuild the reading.
        #
        # v1 replaced only the concept units and shuffled the rest out of the
        # way, which left every other kind on its PDF-derived original — a
        # truncated recap and a shredded example a few units after a properly
        # authored concept. When a file carries los/practice/recap the whole
        # reading is authored, so the whole reading is replaced and the
        # ordinals are rebuilt clean. No shift is needed, and none of the
        # collisions it caused can arise.
        full = any(k in d for k in ("los", "practice", "recap"))
        if full:
            A(f"delete from codex_units where reading_id = {q(reading)};")
        else:
            # v1 file: concepts only. Keep the survivors and shift them past the
            # new units. codex_units has a non-deferrable unique (reading_id,
            # ord) checked per row, so a single "ord + n" collides whenever a
            # target ordinal is still occupied. Park above any real ordinal
            # first to make both legs safe.
            A(f"delete from codex_units where reading_id = {q(reading)} and kind in ('concept', 'example');")
            A(f"update codex_units set ord = ord + {PARK} "
              f"where reading_id = {q(reading)} and kind <> 'los' and ord > 0;")
            A(f"update codex_units set ord = ord - {PARK - n_units} "
              f"where reading_id = {q(reading)} and kind <> 'los' and ord > {PARK};")

        # 2. learning outcomes, pinned at ord 0
        if d.get("los"):
            uid = unit_id(topic, mod, 0, "los")
            A("insert into codex_units (id, reading_id, topic_id, ord, kind, title, est_minutes, payload)")
            A(f"values ({q(uid)}, {q(reading)}, {q(topic)}, 0, 'los', 'Learning Outcomes', 3, "
              f"{jq({'source': 'blocks-v1', 'outcomes': d['los']})})")
            A("on conflict (id) do update set payload = excluded.payload;")

        # 3. concept units at 1..N
        for u in d["units"]:
            uid = unit_id(topic, mod, u["ordinal"])
            payload = {"source": "blocks-v1", "prose_md": ""}
            A(f"insert into codex_units (id, reading_id, topic_id, ord, kind, title, est_minutes, payload)")
            A(f"values ({q(uid)}, {q(reading)}, {q(topic)}, {u['ordinal']}, 'concept', "
              f"{q(u['title'])}, {est_minutes(u['blocks'])}, {jq(payload)})")
            A("on conflict (id) do update set title = excluded.title, "
              "ord = excluded.ord, est_minutes = excluded.est_minutes;")

        # 4. their blocks
        for u in d["units"]:
            uid = unit_id(topic, mod, u["ordinal"])
            A(f"delete from codex_blocks where unit_id = {q(uid)};")
            rows = []
            for b in u["blocks"]:
                rows.append(f"  ({q(uid)}, {b['ord']}, {q(b['block_type'])}, "
                            f"{jq(b['payload'])}, {q(d['source_ref'])}, now(), 'authored')")
            # a unit with no blocks would otherwise emit "values ;"
            if rows:
                A("insert into codex_blocks (unit_id, ord, block_type, payload, source_ref, reviewed_at, reviewed_by)\nvalues")
                A(",\n".join(rows) + ";")

        # 5. practice items, then the recap, after the concepts
        ord_after = n_units
        for it in d.get("practice", []):
            ord_after += 1
            uid = unit_id(topic, mod, it["ordinal"], "practice")
            payload = {"source": "blocks-v1",
                       "vignette": it.get("vignette", ""), "question": it["question"],
                       "choices": it["choices"], "answer": it["answer"],
                       "solution_md": it.get("solution_md", ""),
                       "difficulty": it.get("difficulty", "medium")}
            los = it.get("los")
            A("insert into codex_units (id, reading_id, topic_id, ord, kind, title, est_minutes, los_num, payload)")
            A(f"values ({q(uid)}, {q(reading)}, {q(topic)}, {ord_after}, 'practice', "
              f"{q('Practice — LOS ' + str(los) if los else 'Practice')}, 4, "
              f"{los if los is not None else 'null'}, {jq(payload)})")
            A("on conflict (id) do update set ord = excluded.ord, payload = excluded.payload, "
              "title = excluded.title, los_num = excluded.los_num;")

        if d.get("recap"):
            ord_after += 1
            uid = unit_id(topic, mod, 0, "recap")
            payload = {"source": "blocks-v1",
                       "formulas": d["recap"].get("formulas", []),
                       "los_revisited": d["recap"].get("los_revisited", [])}
            A("insert into codex_units (id, reading_id, topic_id, ord, kind, title, est_minutes, payload)")
            A(f"values ({q(uid)}, {q(reading)}, {q(topic)}, {ord_after}, 'recap', 'Recap', 3, {jq(payload)})")
            A("on conflict (id) do update set ord = excluded.ord, payload = excluded.payload;")
        A("")

    A("commit;")
    return "\n".join(out)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--emit-sql", action="store_true",
                    help="write SQL to stdout (the only supported mode)")
    a = ap.parse_args()
    if not a.emit_sql:
        sys.exit("refusing to run without --emit-sql. This script does not write to the database.")
    print(emit(a.files))
