#!/usr/bin/env python3
"""
Seed Codex typed blocks from block JSON.

    python3 seed_blocks.py blocks_*.json --emit-sql > seed.sql

Emits SQL to stdout. Writes nothing to the database — review the SQL,
then apply it yourself. That is deliberate: this script replaces existing
concept units, and you should see exactly what it removes first.

Strategy
--------
For each reading it touches:
  1. DELETE existing kind='concept' units (they are the flattened prose
     blobs the block system replaces). Their blocks cascade.
  2. INSERT new concept units at ord 1..N in notes order.
  3. Shift surviving units (los / example / practice / recap) to sit
     after the new concepts, preserving their relative order.
     'los' stays pinned at ord 0.
  4. INSERT typed blocks against the new units.

Unit ids are a deterministic hash of (topic, module, ordinal), so re-running
produces identical ids and the ON CONFLICT clauses make it idempotent.
"""
import json, sys, hashlib, argparse

# reading_id per module, from codex_documents where topic_id='alt'
READINGS = {
    "LM1": "9e4f73e51fc88d63",
    "LM2": "ee918d2241cca38f",
    "LM3": "e74131b7a8c16067",
    "LM4": "f74779747e1f9673",
}

def unit_id(topic, module, ordinal):
    """16-char hex, matching the existing id format."""
    return hashlib.sha256(f"{topic}:{module}:{ordinal}:blocks-v1".encode()).hexdigest()[:16]

def q(s):
    """Quote a SQL string literal."""
    return "'" + str(s).replace("'", "''") + "'"

def jq(o):
    """Quote a JSON value as a jsonb literal."""
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"

def _words(o):
    """Count words in payload text only, ignoring JSON structure."""
    if isinstance(o, str):  return len(o.split())
    if isinstance(o, list): return sum(_words(x) for x in o)
    if isinstance(o, dict): return sum(_words(v) for k, v in o.items()
                                       if k not in ("aligns", "variant", "total_rows"))
    return 0

def est_minutes(blocks):
    """
    Technical study material reads at roughly 130 wpm, not the 200+ of casual
    prose. Tables, formulas and worked examples are parsed rather than read,
    so they carry a per-item surcharge in seconds.
    """
    SURCHARGE = {"formula": 25, "worked": 100, "key": 20, "trap": 20, "exam": 20,
                 "table_compare": 20, "table_signal": 15, "table_data": 20}
    seconds = 0
    for b in blocks:
        bt = b["block_type"]
        seconds += _words(b["payload"]) / 130 * 60
        seconds += SURCHARGE.get(bt, 0)
        if bt.startswith("table"):
            seconds += 12 * len(b["payload"].get("rows", []))
        if bt == "worked":
            seconds += 12 * sum(len(x.get("rows", []))
                                for x in b["payload"].get("blocks", [])
                                if x.get("kind") == "table")
    return max(3, min(20, round(seconds / 60)))

def emit(files):
    out = []
    A = out.append
    A("-- Generated by seed_blocks.py. Review before applying.")
    A("-- Replaces flattened 'concept' units with typed blocks.\n")
    A("begin;\n")

    for path in files:
        d = json.load(open(path, encoding="utf8"))
        mod, topic = d["module"], d["topic_id"]
        reading = READINGS.get(mod)
        if not reading:
            sys.exit(f"unknown module {mod} — add it to READINGS")

        n_units = len(d["units"])
        A(f"-- ===== {mod}: {d['module_title']} =====")
        A(f"-- {n_units} units, {sum(len(u['blocks']) for u in d['units'])} blocks")

        # 1. remove the blobs
        A(f"delete from codex_units where reading_id = {q(reading)} and kind = 'concept';")

        # 3. make room: push survivors past the new concepts (los stays at 0)
        A(f"update codex_units set ord = ord + {n_units} "
          f"where reading_id = {q(reading)} and kind <> 'los' and ord > 0;")

        # 2. new concept units
        for u in d["units"]:
            uid = unit_id(topic, mod, u["ordinal"])
            payload = {"source": "blocks-v1", "prose_md": ""}
            A(f"insert into codex_units (id, reading_id, topic_id, ord, kind, title, est_minutes, payload)")
            A(f"values ({q(uid)}, {q(reading)}, {q(topic)}, {u['ordinal']}, 'concept', "
              f"{q(u['title'])}, {est_minutes(u['blocks'])}, {jq(payload)})")
            A("on conflict (id) do update set title = excluded.title, "
              "ord = excluded.ord, est_minutes = excluded.est_minutes;")

        # 4. blocks
        for u in d["units"]:
            uid = unit_id(topic, mod, u["ordinal"])
            A(f"delete from codex_blocks where unit_id = {q(uid)};")
            rows = []
            for b in u["blocks"]:
                rows.append(f"  ({q(uid)}, {b['ord']}, {q(b['block_type'])}, "
                            f"{jq(b['payload'])}, {q(d['source_ref'])}, now(), 'authored')")
            A("insert into codex_blocks (unit_id, ord, block_type, payload, source_ref, reviewed_at, reviewed_by)\nvalues")
            A(",\n".join(rows) + ";")
        A("")

    A("commit;")
    return "\n".join(out)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--emit-sql", action="store_true",
                    help="write SQL to stdout (the only supported mode)")
    a = ap.parse_args()
    if not a.emit_sql:
        sys.exit("refusing to run without --emit-sql. This script does not write to the database.")
    print(emit(a.files))
